name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
        
    - name: setup Docker build
      uses: docker/setup-buildx-action@v3.3.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: api
        path: app

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: fiapfastfood
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}


    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: fiapfastfood/fiap-api:${{ github.event.pull_request.number }}

                
          
